In [3]:
!pip install numpy

^C
     ---------------------------------------- 0.0/60.9 kB ? eta -:--:--
     --------------------------------- ------ 51.2/60.9 kB ? eta -:--:--
     --------------------------------- ------ 51.2/60.9 kB ? eta -:--:--
     --------------------------------- ------ 51.2/60.9 kB ? eta -:--:--
     --------------------------------- ------ 51.2/60.9 kB ? eta -:--:--
     --------------------------------- ------ 51.2/60.9 kB ? eta -:--:--
     --------------------------------- ------ 51.2/60.9 kB ? eta -:--:--
     -------------------------------------- 60.9/60.9 kB 202.6 kB/s eta 0:00:00
   ---------------------------------------- 0.0/16.2 MB ? eta -:--:--
   ---------------------------------------- 0.1/16.2 MB 3.3 MB/s eta 0:00:05
   ---------------------------------------- 0.2/16.2 MB 3.9 MB/s eta 0:00:05
    --------------------------------------- 0.3/16.2 MB 2.3 MB/s eta 0:00:07
    --------------------------------------- 0.4/16.2 MB 3.3 MB/s eta 0:00:05
   - ------------------------

In [5]:
import numpy as np

In [13]:
a=[1,2,3,4,5,6]
a 
type(a)

list

In [14]:
# creating array from list
x=np.array(a)
x
type(x)

numpy.ndarray

In [16]:
a=np.array([[1,2,3],[4,5,6]])


In [17]:
a.shape # returns shape of an array

(2, 3)

In [18]:
print(a)

[[1 2 3]
 [4 5 6]]


In [19]:
a.size   # returns total number of elements in an array

6

In [20]:
a.ndim # gives how many dimension of an array

2

In [25]:
# teranspose
a= a.T # use capital T

In [26]:
a.shape

(3, 2)

In [39]:
a=a.reshape(3,2)  # change the shape of an array , make sure product of elements should be same
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [42]:
a= np.array([[1,2,3],[4,5,6]])
a.shape

(2, 3)

In [43]:
b=np.array([11,12,13,14,15,16])
b.shape

(6,)

In [44]:
b=b.reshape(2,3)
b

array([[11, 12, 13],
       [14, 15, 16]])

In [47]:
c= np.concatenate((a,b))  #use double parantheses
c

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [11, 12, 13],
       [14, 15, 16]])

In [48]:
c.shape

(4, 3)

In [52]:
np.vstack((a,b)) # joins two array vertically (column)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [11, 12, 13],
       [14, 15, 16]])

In [51]:
np.hstack((a,b)) # joins two array horizontally (row)

array([[ 1,  2,  3, 11, 12, 13],
       [ 4,  5,  6, 14, 15, 16]])

In [53]:
c

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [11, 12, 13],
       [14, 15, 16]])

In [72]:
#append
c=np.append(c,[[17,18,19],[20,21,22]])
c

array([ 1, 17, 18, 19, 20, 21, 22])

In [75]:
#delete
c=np.delete(c,[0]) # which array from what index
c

array([17, 18, 19, 20, 21, 22])

In [74]:
# insert
c=np.insert(c,0,1) # which array from what index and value
c

array([ 1, 17, 18, 19, 20, 21, 22])

In [81]:
# arange- it create an array with given size
# slicing single dimension array
x=np.arange(6) #0 to n-1, i.e 0 to 5
x
y= np.arange(2,30,2)  #syntax(lower limit , upper limit, difference)
y
print(x,y)

[0 1 2 3 4 5] [ 2  4  6  8 10 12 14 16 18 20 22 24 26 28]


In [86]:
y=y.reshape(7,2)
y

array([[ 2,  4],
       [ 6,  8],
       [10, 12],
       [14, 16],
       [18, 20],
       [22, 24],
       [26, 28]])

In [87]:
y[0:4]  #slicing using indexing 

array([[ 2,  4],
       [ 6,  8],
       [10, 12],
       [14, 16]])

In [89]:
# random.rand
import numpy as np
a=np.random.rand(4)  # 1D array with positive values 
b=np.random.rand(2,3) # 2D array with positive values
c=np.random.rand(2,2,3) # 3D array with positive values
d=np.random.randn(2,3)  # 12D array with negative and positive values

In [91]:
print(a)

[0.83027942 0.43928398 0.48093834 0.41598164]


In [96]:
#aggregate function
a=np.array([11,12,13,14,15,16])
a

array([11, 12, 13, 14, 15, 16])

In [103]:
print(a.sum())

81


In [102]:
print(a.prod())

5765760


In [97]:
print(a.mean())

np.float64(13.5)

In [104]:
print(a.std())

1.707825127659933


In [105]:
print(a.var())

2.9166666666666665


In [106]:
print(a.min())

11


In [107]:
print(a.max())

16


In [109]:
print(a.all()) # all() returns true if there is a non zero value in an array

True


In [112]:
b= np.zeros((10,10)) # zeros(row,col) create a 10 by 10 matrix with all zero values
b

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [113]:
print(b.all())

False


In [114]:
c=np.eye(3)
c

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [118]:
d=np.eye(5,5,k=-1) # try with k=1 or k=-1
d

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [134]:
b=np.zeros((10,10))    #loops in array
for i in range (10): # range(col value)
    b[i]=i
b

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [139]:
b= b.shape[1]
print(b)

AttributeError: 'int' object has no attribute 'shape'

In [145]:
#cumsum
print('before cumsum',a)
print('after cumsum',a.cumsum())

before cumsum [11 12 13 14 15 16]
after cumsum [11 23 36 50 65 81]


In [146]:
# cumprod
print('before cumprod',a)
print('after cumprod',a.cumprod())

before cumprod [11 12 13 14 15 16]
after cumprod [     11     132    1716   24024  360360 5765760]


In [147]:
import numpy as np

array1 = np.array([1, 2, 3, 4, 5 ])
number = 10

#  number sums up with each array element
result = array1 + number

print(result)
print(type(result))

[11 12 13 14 15]
<class 'numpy.ndarray'>


In [148]:
import time 

start = time.time()

array1 = [1, 2, 3, 4, 5]

for i in range(len(array1)):
    array1[i] =array1[i]+ 10

#print(array1)

end = time.time()

print("For loop time:", end - start)

For loop time: 0.0


In [149]:
import numpy as np
import time

start = time.time()

array1 = np.array([1, 2, 3, 4, 5 ])

result = array1 + 10

#print(result)

end = time.time()

print("Vectorization time:", end - start)

Vectorization time: 0.0


In [150]:
# find square of number in an array
import time
start_time= time.time()
def find_square(x):
    if x < 0:
        return 0
    else:
        return x ** 2


#s=find_square(4)
#s
array1 = [1, 2, 3, 4, 5]
v_func=np.vectorize(find_square)
s=v_func(array1)

print(s)

end_time= time.time()

print("total execution time is",end_time-start_time)

[ 1  4  9 16 25]
total execution time is 0.46408987045288086


In [151]:
#campatibility rules: one of them has a length of 1 or they are equal
#check from right to left
x=np.arange(2,22,2)

#print(x)

y=np.arange(30,40)

w=np.arange(2)

x=x.reshape(2,5)

#y=y.reshape(5,2)  # cannot broadcast
#y=y.reshape(10,1)  # cannot broadcast
y=y.reshape(2,5)

#w=w.reshape(1,2)  #cannot broadcast
w=w.reshape(2,1)
print(w)
z=x+y+w
z

[[0]
 [1]]


array([[32, 35, 38, 41, 44],
       [48, 51, 54, 57, 60]])

In [156]:
#Boolean indexing :In NumPy, boolean indexing allows us to filter elements from an array based on a specific condition.
# boolean mask
a=np.array([23,56,88,1,2,4,10,15])
# boolean mask
bm=a>40
print(bm)
print(a[bm])

[False  True  True False False False False False]
[56 88]


In [154]:
#broadcasting with scalar
a=np.array([[10,20,30],[40,50,60]])
a
#broadcasting with scalar
b=5
c=a+b
c

array([[15, 25, 35],
       [45, 55, 65]])

In [163]:
#use logical and ,or
a=np.array([10,15,47,38,28,48,29,59,98])
bm1=(a%2==0) & (a>40)
#bm2=bm1>40
print(bm1)
print(a[bm1])

[False False False False False  True False False  True]
[48 98]


In [164]:
import numpy as np

# create a 2D  array
array1 = np.array([[1, 7, 9], 
                    [14, 19, 21], 
                    [25, 29, 35]])

# create a boolean mask based on the condition 
# that elements are greater than 9
boolean_mask = array1 > 9

# select only the elements that satisfy the condition
result = array1[boolean_mask]

print(result)
print(boolean_mask)

[14 19 21 25 29 35]
[[False False False]
 [ True  True  True]
 [ True  True  True]]


In [166]:
# update the true value with specified value
a[bm1]=100
a

array([ 10,  15,  47,  38,  28, 100,  29,  59, 100])